### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'assets')

### ISSUE THREAD

**Issue by Tom-H2oThermo** [OfficeDev/OfficeAddinDevKit#11]
**Describe the bug**
When I run "npm start" I'm getting a number of errors.

**To Reproduce**
run "npm build" and "npm start".  At first I was getting about 89 errors with long cryptic error explanations.    this page https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5 says that this issue happens when your webpack module gets upgraded from V4 to V5, which must have happened when I ran "npm build".  That same page said that a solution was to install the _[node-polyfill-webpack-plugin](https://github.com/Richienb/node-polyfill-webpack-plugin)_ which I did.  Then the number of errors were reduced to 10 relatively simple errors, but I don't know how to fix them.

**Expected behavior**
I expected the "npm start" to work and open my Excel app/taskpane.

**Screenshots or logs/output in Terminal**  Please see the errors below.
**PS C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1> npm start
> excel-custom-functions@0.0.1 prestart
> npm run build
> excel-custom-functions@0.0.1 build
> webpack --mode production
C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\webpack\lib\Compilation.js:4706
                        if (buildInfo.assets) {
                                      ^
TypeError: Cannot read properties of undefined (reading 'assets')
    at Compilation.createModuleAssets (C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\webpack\lib\Compilation.js:4706:18)
    at C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\webpack\lib\Compilation.js:3196:13
    at Compilation._runCodeGenerationJobs (C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\webpack\lib\Compilation.js:3351:11)
    at C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\webpack\lib\Compilation.js:3181:12
    at C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\webpack\lib\Compilation.js:3443:6
    at C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\neo-async\async.js:2818:7
    at done (C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\neo-async\async.js:3522:9)
    at C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\webpack\lib\Compilation.js:3404:8
    at C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\webpack\lib\Compilation.js:3521:5
    at C:\Users\tomte\OneDrive\Documents\GitHub\H2oThermo_App-Development1\node_modules\enhanced-resolve\lib\forEachBail.js:39:13

Node.js v18.20.2**

**Environment(please complete the following information):**
 - OS: Microsoft Windows 11 Home
 - Version 10.0.22361
 - VS Code Version 1.94.2
 - Node Version 18.20.2

**Comment by hermanwenhe** [comment]
Is this project created from a hello world template or from a sample in sample gallery?

**Comment by hermanwenhe** [comment]
The `npm build` script won't upgrade the webpack. Have you done the upgrade yourself? After a new project is setup, the only thing you need to do before `npm start` is `npm install`.

**Comment by hermanwenhe** [comment]
Close this issue since there is no further discussion.
